### ISSUE TITLE
Orphaned folders/data in /tmp on remote machines

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#4] opened 2023-06-06 06:02 UTC
When running remote backups (aka slave mode), it happens that BAR does not clean up it's old files in the /tmp-folder correctly.
I noticed that the BAR main instance seems to lose connection to the remote machine right after finishing the job. It looks like some sort of re-connection and can be traced in the logs. However, this leads to re-creation of the folder-structure in /tmp and occationally to orphaned files, too.

Observed with versions 0.22f and up.

**Comment by torsten-rupp** [comment] 2023-06-10 12:45
Excuse my late reply. Thank you a lot for the feedback and bug description. I will have a look on that to reproduce it and find a fix asap.

**Comment by torsten-rupp** [comment] 2023-06-17 12:50
Dear Chris, does the log of the remote backup say something that BAR crashed and was restarted? If just the connection is getting lost, e. g. due to a temporary network problem, a reconnect is done, but this should not cause a recreation of the temporary folder in /tmp. The temporary folder is created once when the remote BAR is started and deleted when it is terminated in a normal way (no crash).

**Comment by ChrisTG742** [comment] 2023-06-17 16:46
Yes, Torsten, indeed it looks like that BAR gets restarted somehow. But there's no trace of a crash visible in the log on the slave machine:

2023-06-16 12:00:31> Start job 'slave-vm' incremental by 'master.local:59840' (master)
2023-06-16 12:21:44> Started BAR 0.22f server slave on 'slave-vm' with 2 worker threads
2023-06-16 12:21:44> Warning: no server password set!
2023-06-16 12:21:44> Ready
2023-06-16 21:03:10> Start job 'slave-vm' incremental by 'master.local:38020' (master)
2023-06-16 21:23:47> Started BAR 0.22f server slave on 'slave-vm' with 2 worker threads
2023-06-16 21:23:47> Warning: no server password set!
2023-06-16 21:23:47> Ready

Do I need to increase log-level? If so, how exactly?

**Comment by torsten-rupp** [comment] 2023-06-18 05:45
Dear Chris. Thank you for the log.

It looks like the BAR instance crashed. There should be something between "Start job..." and "Started BAR...". A normal shutdown would produce at least the log line "Terminate BAR server".

Yes, you could enable all logging by "log = all", but if there is a crash then I fear the log in the file will just stop somewhere. I will try to add some logging for crashes. Maybe this could help to identify the problem.

Are you able to reproduce this issue? If you could reproduce it the following may help me to understand what is going on:

- stop the BAR service (/etc/init.d/barserver stop or systemctl stop barserver)
- start BAR manually in debug mode:
  bar-debug --server --verbose=6 --pid-file /var/run/bar.pid --log=all
  resp.
  bar-debug --server --server-mode=slave --verbose=6 --pid-file /var/run/bar.pid --log=all

If there is a crash this should be visible in the console output. The debug version will print very likely either some "assert" output or a stack trace.

**Comment by ChrisTG742** [comment] 2023-06-20 06:49
At the moment it seems I can't reproduce the error if debug is enabled. Instead, the backup-job always runs into a timeout now?

ERROR: cannot close archive file entry (error: timeout accessing index: INSERT INTO entries (entityId,type,name,timeLastAccess,timeModified,timeLastChanged,userId,groupId,permission,uuidId,size) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) at /tmp/deb-INJ17o/backup-archiver-0.22f/bar/server_io.c, 1970)!

Where is that timeout defined? Can it be changed via bar.cfg?

**Comment by ChrisTG742** [comment] 2023-06-23 06:17
Okay, with that commands I was able to repait the database. Actually, there were a lot of orphaned and a few "invalid" entries. I wonder how this could happen? The database is only abt. 1 week old. I had to purge the old one when I upgraded Postgresql to 14.

However, now I was able to capture the trace logs:

DEBUG ERROR: resource 'databaseHandle' 0x00007f56d94f8ed0 not found in debug list at /tmp/deb-INJ17o/backup-archiver-0.22f/bar/common/database.c, line 12925
  [0x00000000005ed0fd] __cyg_profile_func_exit (<unknown file>:0)
  [0x00000000005c5bc1] <unknown symbol> (bar-debug:0)
  [0x00000000005250b0] <unknown symbol> (bar-debug:0)
  [0x0000000000525229] <unknown symbol> (bar-debug:0)
  [0x000000000043ce84] <unknown symbol> (bar-debug:0)
  [0x0000000000626e09] __wrap_pthread_create (<unknown file>:0)
  [0x00000000006251b8] __cyg_profile_func_exit (<unknown file>:0)
  [0x0000000000008608] start_thread (<unknown file>:0)
  [0x000000000011f132] clone (<unknown file>:0)
INTERNAL ERROR: check resource trace fail - program aborted in file /tmp/deb-INJ17o/backup-archiver-0.22f/bar/common/global.c, line 1200
Abgebrochen

Hope that helps.

**Comment by torsten-rupp** [comment] 2023-06-26 11:27
Dear Chris,

> DEBUG ERROR: resource 'databaseHandle' 0x00007f56d94f8ed0 not found in debug list at /tmp/deb-INJ17o/backup-archiver-0.22f/bar/common/database.c, line 12925 [0x00000000005ed0fd] __cyg_profile_func_exit (:0) [0x00000000005c5bc1] (bar-debug:0) [0x00000000005250b0] (bar-debug:0) [0x0000000000525229] (bar-debug:0) [0x000000000043ce84] (bar-debug:0) [0x0000000000626e09] __wrap_pthread_create (:0) [0x00000000006251b8] __cyg_profile_func_exit (:0) [0x0000000000008608] start_thread (:0) [0x000000000011f132] clone (:0) INTERNAL ERROR: check resource trace fail - program aborted in file /tmp/deb-INJ17o/backup-archiver-0.22f/bar/common/global.c, line 1200 Abgebrochen

This is probably the issue which is fixed with

commit 7d03b45d492b89a57c68716b42a51822e7efbc62
Author: Torsten Rupp <torsten.rupp@macio.de>
Date:   Sat Apr 1 09:49:38 2023 +0200

    fixed invalid database handle in slave mode [debug version only]

I created a release candidate for version 0.22h with some fixes and improvements. Mainly crashes are now logged into the logfile and some fixes with locking and error handling. This is still not a public released, but you can get it from here

http://www.kigen.de/projects/bar/backup-archiver-0.22h+rc1.tar.bz2
http://www.kigen.de/projects/bar/backup-archiver-0.22h+rc1-x86_64.rpm
http://www.kigen.de/projects/bar/backup-archiver-0.22h+rc1-x86_64.deb
http://www.kigen.de/projects/bar/backup-archiver-gui-0.22h+rc1-x86_64.deb
http://www.kigen.de/projects/bar/backup-archiver-gui-0.22h+rc1.zip

for a test. Could you try it with this version again? Thank you.

The issues with the lost entries in the database is already addressed in the release 0.22g, but I still work on that to get a clear view what is happening there. If there is a crash some entries in the database may become incomplete. This could cause the "orphaned" entries.

**Comment by ChrisTG742** [comment] 2023-06-27 07:26
I replaced both instances with the rc1, but now I again get a timeout error accessing the database:

Store '/tmp/bar-CVHncT/archive-smQfQR' to '/data/backup/bar/2023-06-27/xxxxx-I-08-000.bar'...OK (9722617776 bytes)
FAIL
ERROR: cannot update index for storage '/data/backup/bar/2023-06-27/xxxxx-I-08-000.bar' (error: timeout accessing index: UPDATE entriesNewest SET entryId=$1,uuidId=$2,entityId=$3,type=$4,name=$5,timeLastChanged=$6,userId=$7,groupId=$8,permission=$9,size=$10 WHERE id=$11 at /tmp/deb-7epjws/backup-archiver-0.22h+rc1/bar/server_io.c, 1970)!
ERROR: cannot create index for '/data/backup/bar/%Y-%m-%d/xxxxx-%T-%H-###.bar' (error: timeout accessing index: UPDATE entities SET totalEntryCount=$1,totalEntrySize=$2,totalFileCount=$3,totalFileSize=$4,totalImageCount=$5,totalImageSize=$6,totalDirectoryCount=$7,totalLinkCount=$8,totalHardlinkCount=$9,totalHardlinkSize=$10,totalSpecialCount=$11 WHERE id=$12 at /tmp/deb-7epjws/backup-archiver-0.22h+rc1/bar/server_io.c, 1970)!

**Comment by ChrisTG742** [comment] 2023-06-27 11:38
After repairing the database by "bar-index" again, it now completed without errors.
I would let it run until tomorrow to be sure that the issue with the crash is completely gone.

**Comment by ChrisTG742** [comment] 2023-06-28 12:52
I can now confirm that the crash bug is fixed with 0.22h+rc1.
Thanks for your efforts! :)

**Comment by torsten-rupp** [comment] 2023-07-02 09:04
> I can now confirm that the crash bug is fixed with 0.22h+rc1. Thanks for your efforts! :)

Thank you a lot for the feedback and for doing the test again. It seems the original problem was that there was a crash and the temporary files where left. If the crash is now gone then the original problem is solve, too.

I will close this issue and I will create an official release soon.

**Closed** 2023-07-02 09:04 UTC
