### ISSUE TITLE
barcontrol 25: Java Nullpointer error when closing GUI on Windows x64

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#15] opened 2024-10-26 18:41 UTC
Just got the following error when closing the GUI:
![grafik](https://github.com/user-attachments/assets/9006af7e-7bea-4bd9-9a39-385ea91f119e)

Here's the complete stacktrace as text:

``
  org.eclipse.swt.widgets.Widget.sendSelectionEvent(Unknown Source)
  org.eclipse.swt.widgets.TabFolder.wmNotifyChild(Unknown Source)
  org.eclipse.swt.widgets.Control.wmNotify(Unknown Source)
  org.eclipse.swt.widgets.Composite.wmNotify(Unknown Source)
  org.eclipse.swt.widgets.Control.WM_NOTIFY(Unknown Source)
  org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
  org.eclipse.swt.widgets.Canvas.windowProc(Unknown Source)
  org.eclipse.swt.widgets.Decorations.windowProc(Unknown Source)
  org.eclipse.swt.widgets.Shell.windowProc(Unknown Source)
  org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
  org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
  org.eclipse.swt.internal.win32.OS.CallWindowProc(Unknown Source)
  org.eclipse.swt.widgets.TabFolder.callWindowProc(Unknown Source)
  org.eclipse.swt.widgets.Widget.wmLButtonDown(Unknown Source)
  org.eclipse.swt.widgets.Control.WM_LBUTTONDOWN(Unknown Source)
  org.eclipse.swt.widgets.Composite.WM_LBUTTONDOWN(Unknown Source)
  org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
  org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
  org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
  org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
  org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
  BARControl.run(BARControl.java:5051)
  BARControl.<init>(BARControl.java:7694)
  BARControl.main(BARControl.java:7753)
``

Note: Some INDEX work was running at the moment. BAR seemed to be busy upgrading an imported index-db from an earlier version:

``
2024-10-26 20:38:06> INDEX: 58.8%, estimated rest time 0h:00min:00s
``

BTW, the "estimated rest time" is always displayed as 0h:00min:00s. Another bug?

**Comment by ChrisTG742** [comment] 2024-10-26 18:45
After that crash I'm no longer able the start the GUI again. It closes instantly again with following output in barcontrol.log:

Date/Time: Sat Oct 26 20:43:29 CEST 2024
Version: 25 (55fc7b777e12ee15d3851512b40f1630a7d1981f)
Protocol version: 8.0
Java version: 11.0.18
Error: 18446743677527091818
  ValueMap.getLong(StringParser.java:180)
  ValueMap.getLong(StringParser.java:206)
  TabRestore$UpdateStorageTreeTableThread$6.handle(TabRestore.java:2234)
  ReadThread.run(BARServer.java:954)
Caused by:
  java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  java.base/java.lang.Long.parseLong(Long.java:692)
  java.base/java.lang.Long.parseLong(Long.java:817)
  ValueMap.getLong(StringParser.java:169)
  ValueMap.getLong(StringParser.java:206)
  TabRestore$UpdateStorageTreeTableThread$6.handle(TabRestore.java:2234)
  ReadThread.run(BARServer.java:954)
---

**Comment by ChrisTG742** [comment] 2024-10-26 19:21
Even worse: After restarting barserver, all backups in the database are marked as incomplete and purged. Luckily I was fast enough to stop BAR again before it actually could physically delete my backups on the strorage:

2024-10-26 20:51:14> Started BAR 25 server on 'xxxxx' with 4 worker threads
2024-10-26 20:51:14> INDEX: Opened index database 'sqlite3:/var/lib/bar/index.db' (version 8)
2024-10-26 20:51:14> INDEX: Started initial clean-up index database
2024-10-26 20:51:14> INDEX: Start clean-up duplicate meta data
2024-10-26 20:51:14> INDEX: Done clean-up duplicate meta data
2024-10-26 20:51:14> INDEX: Start clean-up incomplete updates
2024-10-26 20:51:14> INDEX: Done clean-up incomplete updates
2024-10-26 20:51:14> INDEX: Start clean-up incomplete created archives
2024-10-26 20:51:14> INDEX: Purged incomplete storage #19: '/mnt/backup/2020-09-03/userdata-F-000.bar'
2024-10-26 20:51:14> INDEX: Purged incomplete storage #35: '/mnt/backup/2020-09-03/userdata-F-001.bar'
2024-10-26 20:51:14> INDEX: Purged incomplete storage #51: '/mnt/backup/2020-09-03/userdata-F-002.bar'
2024-10-26 20:51:14> INDEX: Purged incomplete storage #67: '/mnt/backup/2020-09-03/userdata-F-003.bar'
2024-10-26 20:51:14> INDEX: Purged incomplete storage #83: '/mnt/backup/2020-09-03/userdata-F-004.bar'
2024-10-26 20:51:15> INDEX: Purged incomplete storage #99: '/mnt/backup/2020-09-03/userdata-F-005.bar'
...
This looks like some serious problems. I think I will not start v25 again until it is clear what's happing here.

**Comment by ChrisTG742** [comment] 2024-10-26 19:31
Okay, I was brave enough to re-run barserver (with chmod -w and chattr +i on all backup files) and after these kind of entries in bar.log the GUI now runs again, but all listed backups are gone now.

2024-10-26 21:23:18> INDEX: Removed storage #19 from index: /mnt/backup/2020-09-03/userdata-F-000.bar, created at Thu 03 Sep 2020 08:23:41 PM CEST
2024-10-26 21:23:20> INDEX: Removed storage #35 from index: /mnt/backup/2020-09-03/userdata-F-001.bar, created at Thu 03 Sep 2020 08:30:22 PM CEST
2024-10-26 21:23:22> INDEX: Removed storage #51 from index: /mnt/backup/2020-09-03/userdata-F-002.bar, created at Thu 03 Sep 2020 08:34:55 PM CEST
2024-10-26 21:23:23> INDEX: Removed storage #67 from index: /mnt/backup/2020-09-03/userdata-F-003.bar, created at Thu 03 Sep 2020 08:39:29 PM CEST
2024-10-26 21:23:25> INDEX: Removed storage #83 from index: /mnt/backup/2020-09-03/userdata-F-004.bar, created at Thu 03 Sep 2020 08:44:19 PM CEST
2024-10-26 21:23:26> INDEX: Removed storage #99 from index: /mnt/backup/2020-09-03/userdata-F-005.bar, created at Thu 03 Sep 2020 08:48:58 PM CEST
...

Also, the automatic re-indexing is not triggered for some reason.

**Comment by torsten-rupp** [comment] 2024-10-27 00:32
It seems for some reason a number in the database (here totalSize) is negative, thus returned to the GUI as 18446743677527091818 which cause the NumberFormatException. I can catch the exception, but the real reason is in the database data. You mentioned some index upgrade is running. Maybe it is an intermediate state.

**Comment by torsten-rupp** [comment] 2024-10-27 00:38
BTW: the log message

INDEX: Removed storage...

does not mean the archives are deleted (this should never happen except an archive is expired), but the storage is removed from the database index. The reason for that could be that the storage in the database has an invalid state or it could not be found anymore on the mounted device.

Are there any log entries for a re-indexing after restarting barserver?

**Comment by torsten-rupp** [comment] 2024-10-27 06:01
Avoid the NumberFormatException with commit dbf5631 on release/25

**Comment by torsten-rupp** [comment] 2024-10-27 06:42
Concerning:

2024-10-26 20:38:06> INDEX: 58.8%, estimated rest time 0h:00min:00s

I created another bug entry for this:

https://github.com/torsten-rupp/bar/issues/17

**Comment by ChrisTG742** [comment] 2024-10-27 13:06
> BTW: the log message
> 
> INDEX: Removed storage...
> 
> does not mean the archives are deleted (this should never happen except an archive is expired), but the storage is removed from the database index. The reason for that could be that the storage in the database has an invalid state or it could not be found anymore on the mounted device.
> 
> Are there any log entries for a re-indexing after restarting barserver?

Yes, there are. It seems that the upgrade-conversion actually made all entries invalid. That would explain the Pruge incomplete/Remove storage and re-indexing later.
I upgraded from 24a to 25.

**Comment by torsten-rupp** [comment] 2024-10-27 16:12
I mean the storages are removed from the database index, but I did not observed that the archive files on the hard disk are deleted. Thus only the index is broken.

It seems there is a problem with the database upgrade which happen when switching from 24x to 25 (switch from version 7 to 8). This is of course bad, but BAR should re-create the index entries by reading all archives files which are found in some destination directory of a job.

I will try to reproduce this in some way.

**Comment by torsten-rupp** [comment] 2024-11-01 02:51
I was able to reproduce an import problem which I fixed with

https://github.com/torsten-rupp/bar/issues/16

Also the rest time issue with:

https://github.com/torsten-rupp/bar/issues/17

**Comment by torsten-rupp** [comment] 2024-11-01 02:52
The Null-Pointer-Exception is still difficult. The trace just says it is somewhere in the SWT-library executed in the event-loop, but nothing which is related to BARControl itself.

Do you see this exception always?

**Comment by ChrisTG742** [comment] 2024-11-02 12:00
> The Null-Pointer-Exception is still difficult. The trace just says it is somewhere in the SWT-library executed in the event-loop, but nothing which is related to BARControl itself.
> 
> Do you see this exception always?

Nope, it was only displayed once when the GUI was open while the conversion-import of the database was running. I closed the GUI, because all lists where empty, so I thought something must have been stuck. When closing in this state, the error was displayed.

**Comment by torsten-rupp** [comment] 2024-11-08 02:05
Thank you.

It looks like the Null-Pointer-Exception occurred in some thread when the GUI was closed. Unfortunatelly I was not able to reproduce it now, but I checked the code again for possible reasons where this could happen and added some more catch handlers. Thus I close this issue with commit aa4fca8c1e31017ffe295fac1518515428dcfac8.

**Closed by torsten-rupp** 2024-11-08 02:05 UTC
Labels: bug, confirmed, BARControl
